steps:
  # Étape 1 : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'src/Dockerfile', '-t', 'europe-west9-docker.pkg.dev/$PROJECT_ID/api/api-image', '.']

  # Étape 2 : Push de l'image dans Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/$PROJECT_ID/api/api-image']

  # Étape 3 : Déploiement automatique sur GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "netflix-cluster" --zone "europe-west9-a" --project "$PROJECT_ID"
        kubectl apply -f k8s/
        kubectl set image deployment/api-node api-node=europe-west9-docker.pkg.dev/$PROJECT_ID/api/api-image

images:
  - 'europe-west9-docker.pkg.dev/$PROJECT_ID/api/api-image'

options:
  logging: CLOUD_LOGGING_ONLY
