services:
  api_node:
    # Montre le code local pour hot reload
    volumes:
      - .:/app
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"

  mongodb:
    ports:
      - "27017:27017"

  load-test:
    container_name: load_test
    build:
      context: ./tests/load
      dockerfile: Dockerfile
    image: cloud_administration_load_test
    volumes:
      - ./tests:/tests
    command: python /tests/load/stress_test.py
    networks:
      - netflix_net
    depends_on:
      - api_node
